#!/bin/bash

# Swagger 文档自动更新脚本
# 用途: 自动将 swagger.yaml 转换为 swagger.json 并更新 docs.go
# 使用: ./update-swagger-docs.sh

set -e

echo "🔄 开始更新 Swagger 文档..."
echo ""

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# 检查必要的文件
if [ ! -f "docs/swagger.yaml" ]; then
    echo -e "${RED}❌ 错误: 找不到 docs/swagger.yaml${NC}"
    exit 1
fi

echo -e "${YELLOW}📝 步骤 1: 验证 YAML 语法${NC}"
if command -v yamllint &> /dev/null; then
    if yamllint docs/swagger.yaml; then
        echo -e "${GREEN}✅ YAML 语法正确${NC}"
    else
        echo -e "${RED}❌ YAML 语法错误${NC}"
        exit 1
    fi
else
    echo -e "${YELLOW}⚠️  yamllint 未安装，跳过 YAML 验证${NC}"
fi

echo ""
echo -e "${YELLOW}📝 步骤 2: 转换 YAML 为 JSON${NC}"

# 尝试使用 yq 转换
if command -v yq &> /dev/null; then
    yq eval -o=json docs/swagger.yaml > docs/swagger.json
    echo -e "${GREEN}✅ 使用 yq 转换成功${NC}"
elif command -v python3 &> /dev/null; then
    python3 << 'PYTHON_EOF'
import yaml
import json
import sys

try:
    with open('docs/swagger.yaml', 'r', encoding='utf-8') as f:
        yaml_data = yaml.safe_load(f)
    
    with open('docs/swagger.json', 'w', encoding='utf-8') as f:
        json.dump(yaml_data, f, ensure_ascii=False, indent=2)
    
    print("✅ 使用 Python 转换成功")
except Exception as e:
    print(f"❌ 转换失败: {e}", file=sys.stderr)
    sys.exit(1)
PYTHON_EOF
else
    echo -e "${RED}❌ 需要安装 yq 或 Python 3${NC}"
    echo "   macOS: brew install yq"
    echo "   Linux: apt-get install yq"
    exit 1
fi

echo ""
echo -e "${YELLOW}📝 步骤 3: 验证 JSON 语法${NC}"

if command -v python3 &> /dev/null; then
    if python3 -m json.tool docs/swagger.json > /dev/null 2>&1; then
        echo -e "${GREEN}✅ JSON 格式正确${NC}"
    else
        echo -e "${RED}❌ JSON 格式错误${NC}"
        exit 1
    fi
elif command -v jq &> /dev/null; then
    if jq empty docs/swagger.json 2>/dev/null; then
        echo -e "${GREEN}✅ JSON 格式正确${NC}"
    else
        echo -e "${RED}❌ JSON 格式错误${NC}"
        exit 1
    fi
else
    echo -e "${YELLOW}⚠️  跳过 JSON 验证${NC}"
fi

echo ""
echo -e "${YELLOW}📝 步骤 4: 更新 docs.go${NC}"

# 读取 swagger.json 内容
SWAGGER_JSON=$(cat docs/swagger.json)

# 创建新的 docs.go
cat > docs/docs.go << 'EOF'
// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `
EOF

# 添加 JSON 内容
echo "$SWAGGER_JSON" >> docs/docs.go

cat >> docs/docs.go << 'EOF'
`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TgoRTC Server API",
	Description:      "基于 LiveKit 的音视频服务 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register("swagger", SwaggerInfo)
}
EOF

echo -e "${GREEN}✅ docs.go 已更新${NC}"

echo ""
echo -e "${YELLOW}📝 步骤 5: 构建项目${NC}"

if go build -o tgo-rtc-server 2>&1; then
    echo -e "${GREEN}✅ 构建成功${NC}"
else
    echo -e "${RED}❌ 构建失败${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}✅ 所有步骤完成！${NC}"
echo ""
echo "📊 更新摘要:"
echo "  - docs/swagger.yaml: 已验证"
echo "  - docs/swagger.json: 已更新"
echo "  - docs/docs.go: 已更新"
echo "  - 项目: 已构建"
echo ""
echo "🚀 启动服务:"
echo "  ./tgo-rtc-server"
echo ""
echo "📖 访问 Swagger UI:"
echo "  http://localhost:8080/swagger/index.html"

