// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "openapi": "3.0.0",
  "info": {
    "title": "{{.Title}}",
    "description": "{{escape .Description}}",
    "version": "{{.Version}}",
    "contact": {
      "name": "API Support",
      "url": "https://github.com/TgoRTC/TgoRTCServer"
    }
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "本地开发环境"
    },
    {
      "url": "https://livekit.example.com",
      "description": "生产环境（通过 Caddy 反向代理）"
    },
    {
      "url": "http://livekit.example.com",
      "description": "生产环境（HTTP）"
    }
  ],
  "tags": [
    {
      "name": "房间管理",
      "description": "房间相关的 API 接口"
    },
    {
      "name": "参与者管理",
      "description": "参与者相关的 API 接口"
    },
    {
      "name": "Webhook",
      "description": "Webhook 相关的 API 接口"
    }
  ],
  "paths": {
    "/api/v1/rooms": {
      "post": {
        "tags": ["房间管理"],
        "summary": "创建房间",
        "description": "创建一个新的音视频房间",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["source_channel_id", "creator"],
                "properties": {
                  "source_channel_id": {"type": "string", "example": "channel_123"},
                  "source_channel_type": {"type": "integer", "example": 0},
                  "creator": {"type": "string", "example": "user_001"},
                  "room_id": {"type": "string", "example": "room_abc123"},
                  "rtc_type": {"type": "integer", "example": 1},
                  "invite_on": {"type": "integer", "example": 1},
                  "max_participants": {"type": "integer", "example": 2},
                  "uids": {"type": "array", "items": {"type": "string"}, "example": ["user_002", "user_003"]}
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "房间创建成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "room_id": {"type": "string"},
                    "creator": {"type": "string"},
                    "token": {"type": "string"},
                    "url": {"type": "string"},
                    "status": {"type": "integer"},
                    "created_at": {"type": "string"},
                    "max_participants": {"type": "integer"},
                    "timeout": {"type": "integer"}
                  }
                }
              }
            }
          },
          "400": {"description": "请求参数错误"},
          "500": {"description": "服务器内部错误"}
        }
      }
    },
    "/api/v1/rooms/{room_id}/invite": {
      "post": {
        "tags": ["房间管理"],
        "summary": "邀请参与者",
        "parameters": [{"name": "room_id", "in": "path", "required": true, "schema": {"type": "string"}}],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["uids"],
                "properties": {"uids": {"type": "array", "items": {"type": "string"}}}
              }
            }
          }
        },
        "responses": {
          "200": {"description": "邀请成功"},
          "400": {"description": "请求参数错误"},
          "404": {"description": "房间不存在"}
        }
      }
    },
    "/api/v1/rooms/{room_id}/join": {
      "post": {
        "tags": ["参与者管理"],
        "summary": "加入房间",
        "parameters": [{"name": "room_id", "in": "path", "required": true, "schema": {"type": "string"}}],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["uid"],
                "properties": {"uid": {"type": "string"}}
              }
            }
          }
        },
        "responses": {
          "200": {"description": "加入房间成功"},
          "400": {"description": "请求参数错误"},
          "404": {"description": "房间不存在"}
        }
      }
    },
    "/api/v1/rooms/{room_id}/leave": {
      "post": {
        "tags": ["参与者管理"],
        "summary": "离开房间",
        "parameters": [{"name": "room_id", "in": "path", "required": true, "schema": {"type": "string"}}],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["uid"],
                "properties": {"uid": {"type": "string"}}
              }
            }
          }
        },
        "responses": {
          "200": {"description": "离开房间成功"},
          "400": {"description": "请求参数错误"},
          "404": {"description": "房间或参与者不存在"}
        }
      }
    },
    "/api/v1/participants/calling": {
      "post": {
        "tags": ["参与者管理"],
        "summary": "查询用户通话状态",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["uids"],
                "properties": {"uids": {"type": "array", "items": {"type": "string"}}}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "查询成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "room_id": {"type": "string", "description": "房间 ID"},
                      "uid": {"type": "string", "description": "用户 ID"},
                      "status": {"type": "integer", "description": "参与者状态（0: 邀请中, 1: 已加入, 2: 已拒绝, 3: 已挂断, 4: 超时, 5: 未接听, 6: 已取消）"}
                    }
                  }
                }
              }
            }
          },
          "400": {"description": "请求参数错误"}
        }
      }
    },
    "/api/v1/webhooks/livekit": {
      "post": {
        "tags": ["Webhook"],
        "summary": "LiveKit Webhook",
        "requestBody": {
          "required": true,
          "content": {"application/json": {"schema": {"type": "object"}}}
        },
        "responses": {
          "200": {"description": "事件处理成功"},
          "400": {"description": "事件解析失败"},
          "401": {"description": "验证失败"}
        }
      }
    },
    "/api/v1/webhooks/logs/stats": {
      "get": {
        "tags": ["Webhook"],
        "summary": "获取 Webhook 日志统计",
        "responses": {
          "200": {"description": "获取成功"},
          "500": {"description": "服务器内部错误"}
        }
      }
    },
    "/api/v1/webhooks/logs/cleanup": {
      "post": {
        "tags": ["Webhook"],
        "summary": "清理 Webhook 日志",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["retention_days"],
                "properties": {"retention_days": {"type": "integer", "minimum": 1}}
              }
            }
          }
        },
        "responses": {
          "200": {"description": "日志清理成功"},
          "400": {"description": "请求参数错误"},
          "500": {"description": "服务器内部错误"}
        }
      }
    }
  }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "livekit.example.com",
	BasePath:         "/api/v1",
	Schemes:          []string{"https", "http"},
	Title:            "TgoRTC Server API",
	Description:      "基于 LiveKit 的音视频服务 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register("swagger", SwaggerInfo)
}
